site_name: LicitAL
site_url: https://github.com/unb-mds/2023-2-Squad03/tree/gh-pages
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search
nav:
  - Introdução: "index.md"
  - Arquitetura: "Pages/arquitetura/2023-10-20-arquitetura.md"
  - Backlog: "Pages/backlog/2023-10-20-backlog.md"
  - Branches: "Pages/branches/2023-10-20-branches.md"
  - Comunicação: "Pages/comunicacao/2023-10-20-comunicação.md"
  - Personas: "Pages/personas/2023-10-20-personas.md"
  - Protótipo: "Pages/prototipo/2023-10-20-prototipo.md"
  - Protótipo: "Pages/prototipo/2023-10-20-prototipo.md"
  - Sprints:
    - Sprint 1: "Pages/sprints/2023-10-20-sprint1.md"
    - Sprint 2: "Pages/sprints/2023-10-20-sprint2.md"
    - Sprint 3: "Pages/sprints/2023-10-20-sprint3.md"
    - Sprint 4: "Pages/sprints/2023-10-20-sprint4.md"
    - Sprint 5: "Pages/sprints/2023-10-20-sprint5.md"
    - Sprint 6: "Pages/sprints/2023-10-20-sprint6.md"
    - Sprint 7: "Pages/sprints/2023-10-20-sprint7.md"
  - StoryMap: "Pages/storymap/2023-10-20-storymap.md"

