site_name: Guia UnB
site_url: https://github.com/unb-mds/2023-2-Squad03/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search
nav:
  - Introdução: "index.md"
  - Arquitetura: "docs/Pages/arquitetura/2023-05-06-arquitetura.md"
  - Backlog: "docs/Pages/backlog/2023-05-06-backlog.md"
  - Branches: "docs/Pages/branches/2023-05-04-branches.md"
  - Comunicação: "docs/Pages/comunicacao/2023-05-04-plano-de-comunicação.md"
  - Personas: "docs/Pages/personas/2023-05-23-documento-de-personas.md"
  - Protótipo: "docs/Pages/prototipo/2023-05-11-documento-de-prototipo.md"
  - Sprints:
    - Sprint 0:
      - Planejamento: "docs/Pages/sprints/sprint00/2023-05-06-planejamento.md"
      - Resultado: "docs/Pages/sprints/sprint00/2023-05-06-resultados.md"
    - Sprint 1:
      - Planejamento: "docs/Pages/sprints/sprint01/2023-05-06-planejamento.md"
      - Resultado: "docs/Pages/sprints/sprint01/2023-05-06-resultado.md"
    - Sprint 2:
      - Planejamento: "docs/Pages/sprints/sprint02/2023-05-06-planejamento.md"
      - Resultado: "docs/Pages/sprints/sprint02/2023-05-06-resultado.md"
    - Sprint 3:
      - Planejamento: "docs/Pages/sprints/sprint03/2023-05-06-planejamento.md"
      - Resultado: "docs/Pages/sprints/sprint03/2023-05-06-resultados.md"
    - Sprint 4:
      - Planejamento: "docs/Pages/sprints/sprint04/2023-05-06-planejamento.md"
      - Resultado: "docs/Pages/sprints/sprint04/2023-05-06-resultados.md"
    - Sprint 5:
      - Planejamento: "Pages/sprints/sprint05/2023-05-06-planejamento.md"
      - Resultado: "Pages/sprints/sprint05/2023-05-06-resultados.md"
    - Sprint 6:
      - Planejamento: "docs/Pages/sprints/sprint06/2023-05-11-planejamentos.md"
      - Resultado: "docs/Pages/sprints/sprint06/2023-05-11-resultados.md"
    - Sprint 7:
      - Planejamento: "docs/Pages/sprints/sprint07/2023-07-06-planejamentos.md"
      - Resultado: "docs/Pages/sprints/sprint07/2023-07-06-resultados.md"
  - StoryBoard: "docs/Pages/storyboard/2023-05-23-storyboard.md"
  - Usuário: "docs/Pages/usuario/2023-05-23-perfil-de-usuário.md"

